# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kde_da <- function(xnew, groups, x, h, ncores = 1L) {
    .Call(`_kernda_kde_da`, xnew, groups, x, h, ncores)
}

