// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kde_da
Rcpp::IntegerMatrix kde_da(const Rcpp::NumericVector& xnew, const Rcpp::IntegerVector& groups, const Rcpp::NumericVector& x, const Rcpp::NumericVector& h, int ncores);
RcppExport SEXP _kernda_kde_da(SEXP xnewSEXP, SEXP groupsSEXP, SEXP xSEXP, SEXP hSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type xnew(xnewSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(kde_da(xnew, groups, x, h, ncores));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_kernda_kde_da", (DL_FUNC) &_kernda_kde_da, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_kernda(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
